# Model arguments
model_name_or_path: Qwen/Qwen3-1.7B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
# We edit the DeepSeek chat template to ensure (a) the reasoning block within <think> and </think> is included in the completion and (b) the <think> tag is not part of the prefill so that the format reward works
dataset_name: Neelectric/OpenR1-Math-220k_extended_Llama3_4096toks
dataset_config: default
dataset_prompt_column: problem
system_prompt: "You are a helpful AI Assistant that provides well-reasoned and detailed responses. You first think about the reasoning process as an internal monologue and then provide the user with the answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>"

# VLLM settings
# vllm_dtype: bfloat16
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.1
vllm_tensor_parallel_size: 1
vllm_importance_sampling_correction: true

# GRPO trainer config
bf16: true
fp16: false
beta: 0.01
epsilon: 0.2
epsilon_high: 0.28
disable_dropout: true
do_eval: false
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
importance_sampling_level: "sequence"
learning_rate: 1.0e-06
loss_type: "dr_grpo"
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: constant_with_warmup
lr_scheduler_kwargs:
  min_lr_rate: 0.1
mask_truncated_completions: true
max_completion_length: 4096
max_grad_norm: 0.2
max_prompt_length: 2048
max_steps: -1
num_generations: 8
num_iterations: 1
num_train_epochs: 1
output_dir: data/Qwen/Qwen3-1.7B_GRPO_MoT_mathv00.01
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
report_to:
- wandb
reward_funcs:
- accuracy
- format
reward_weights:
- 1.0
- 0.25
save_strategy: "steps"
save_steps: 0.05
save_total_limit: 1
scale_rewards: false
shuffle_dataset: true
seed: 42
temperature: 0.7
use_liger_kernel: false #NotImplementedError: Liger Kernels currently only support token-level importance sampling. Please set`importance_sampling_level` to 'token'.
warmup_ratio: 0.05
