model_parameters:
  model_name: "Neelectric/Llama-3.1-8B-Instruct_SFT_MoT_mathv00.04"
  dtype: "bfloat16"
  data_parallel_size: 1
  gpu_memory_utilization: 0.9
  max_model_length: 32768
  use_chat_template: true

generation_parameters:
  max_new_tokens: 32768
  temperature: 0.6
  top_p: 0.95

metric_options:
  # Override num_samples for math metrics
  maj_at_4_math:
    num_samples: 1