# Model arguments
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
model_revision: main
dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
# We edit the DeepSeek chat template to ensure (a) the reasoning block within <think> and </think> is included in the completion and (b) the <think> tag is not part of the prefill so that the format reward works
dataset_name: Neelectric/OpenR1-Math-220k_extended_Llama3_4096toks
dataset_config: default
dataset_prompt_column: problem
system_prompt: "You are a helpful AI Assistant that provides well-reasoned and detailed responses. You first think about the reasoning process as an internal monologue and then provide the user with the answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>"

# VLLM settings
# vllm_dtype: bfloat16
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.4
vllm_tensor_parallel_size: 1
vllm_importance_sampling_correction: true
# vllm_model_impl: "transformers"

# GRPO trainer config
cast_lm_head_to_fp32: false #this can cause the following
# [rank1]:   File "/home/user/repos/open-r1_safety/openr1_clone/lib/python3.11/site-packages/transformers/models/olmo2/modeling_olmo2.py", line 455, in forward              [40/3403]
# [rank1]:     logits = self.lm_head(hidden_states[:, slice_indices,
# [rank1]:   File "/home/user/repos/open-r1_safety/openr1_clone/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 125, in forward  
# [rank1]:     return F.linear(input, self.weight, self.bias)                                                                                                                         
# [rank1]: RuntimeError: expected mat1 and mat2 to have the same dtype, but got: float != c10::BFloat16
bf16: true
fp16: false

callbacks:
- push_to_hub_revision
beta: 0.01
epsilon: 0.2
epsilon_high: 5.0
disable_dropout: true
do_eval: false
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Neelectric/Llama-3.1-8B-Instruct_GRPO_Math-220k${VERSION}
hub_model_revision: ${VERSION}
hub_strategy: every_save
importance_sampling_level: "sequence"
learning_rate: 1.0e-06
loss_type: "cispo"
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: constant_with_warmup
lr_scheduler_kwargs:
  min_lr_rate: 0.1
mask_truncated_completions: true
max_completion_length: 4096
max_grad_norm: 0.2
max_prompt_length: 2048
max_steps: -1
num_completions_to_print: 4
num_generations: 16
num_iterations: 1
num_train_epochs: 1
output_dir: data/Neelectric/Llama-3.1-8B-Instruct_GRPO_Math-220k${VERSION}
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 4
report_to:
- wandb
reward_funcs:
- accuracy
- format
# - tag_count
reward_weights:
- 1.0
- 0.25
# - 0.05
run_name: Neelectric/Llama-3.1-8B-Instruct_GRPO_Math-220k${VERSION}
save_strategy: "steps"
save_steps: 0.05
save_total_limit: 1
scale_rewards: "batch"
shuffle_dataset: true
seed: 42
temperature: 0.7
torch_compile: false
use_liger_kernel: false #NotImplementedError: Liger Kernels currently only support token-level importance sampling. Please set`importance_sampling_level` to 'token'.
wandb_entity: Neelectric
wandb_project: open-r1_safety
wandb_log_unique_prompts: True
warmup_ratio: 0.05